### ISSUE TITLE
Does this anything ??

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/can-child-nodes#13]
What is that for if you want childNodes of a given node there are existing apis??

https://www.w3schools.com/jsref/prop_node_childnodes.asp

**Comment by phillipskevin** [comment]
yes, this uses `Node.childNodes`. This package is used to normalize the behavior between the DOM and can-simple-dom.

**Comment by justinbmeyer** [comment]
We could get rid of it in browsers that support proxy. Can-simple-dom could use Proxy for their `childNodes`
